# name: $(BuildID)

trigger:
  batch: true
  branches:
    include:
    - feat/pipeline
    - main
  paths:
    exclude:
    - README.md

variables:
  serviceConnectionName: nuxt-ssr-app-test
  startupCommand: node_modules/.bin/nuxt start
  webappName: nuxt-ssr-app-test

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- script: npm install --production
- script: npm run build

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  artifact: drop

- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy'
  inputs:
    azureSubscription: $(serviceConnectionName)
    appType: webAppLinux
    appName: $(webappName)
    runtimeStack: 'NODE|10.10'
    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
    startUpCommand: $(startupCommand)
