stages:
- stage:
  displayName: Confirm Deployment

  jobs:
  - job: firstTry
    displayName: 'Attempt #1'
    continueOnError: true # --> "SucceededWithIssues"
    steps:
    - template: ./check-website.steps.yaml

  - job: secondTry
    displayName: 'Attempt #2'
    dependsOn: firstTry
    continueOnError: true # --> "SucceededWithIssues"
    condition: eq(dependencies.firstTry.result,'SucceededWithIssues') # only if 1st attempt fails
    steps:
    - template: ./check-website.steps.yaml

  # No `continueOnError` to finally fail pipeline
  - job: finalAttempt
    dependsOn: secondTry
    condition: eq(dependencies.secondTry.result,'SucceededWithIssues') # only if 2nd attempt fails
    displayName: 'Final Attempt'
    steps:
    - template: ./check-website.steps.yaml