stages:
- stage:
  displayName: Confirm Deployment

  jobs:
  - job: firstTry
    displayName: 'Attempt #1'
    continueOnError: true
    steps:
    - template: ./check-website.steps.yaml

  - job: secondTry
    displayName: 'Attempt #2'
    dependsOn: firstTry
    continueOnError: true
    condition: failed()
    steps:
    - template: ./check-website.steps.yaml

  - job: finalAttempt
    dependsOn: secondTry
    condition: failed()
    displayName: 'Final Attempt'
    steps:
    - template: ./check-website.steps.yaml