stages:
- stage:
  displayName: Confirm Deployment

  jobs:
  - job: try1
    displayName: 'Attempt #1'
    continueOnError: true
    steps:
    - template: ./check-website.steps.yaml

  - job: try2
    dependsOn: try1
    displayName: 'Attempt #2'
    continueOnError: true
    steps:
    - template: ./check-website.steps.yaml

  - job: finalAttempt
    dependsOn: try2
    displayName: 'Final Attempt'
    steps:
    - template: ./check-website.steps.yaml